### ISSUE TITLE
key problem for Chinese input

### ISSUE THREAD

**Issue by iLoveBug** [bustle/mobiledoc-kit#703] opened 2019-12-17 09:05 UTC
there is an annoying problem when I try to input some Chinese word. for example:

I want to input the word "好", which should be composed by an input with "hao", but the first "h" will be duplicated in the value, as shown in the screenshot.

![截屏2019-12-17下午5 02 00](https://user-images.githubusercontent.com/40977151/70980961-36fc5300-20ef-11ea-91f0-9672914c0dd8.png)

**Comment by apfelbox** [comment] 2019-12-18 09:32
Is this a duplicate of https://github.com/bustle/mobiledoc-kit/issues/548 ?

**Comment by kevinansfield** [comment] 2019-12-18 13:52
Closing as a duplicate of https://github.com/bustle/mobiledoc-kit/issues/589

**Closed by kevinansfield** 2019-12-18 13:52 UTC

**Comment by iLoveBug** [comment] 2019-12-19 04:14
After search the list, I realized this is a long story more than 2 years, and no one really fix this problem. So I gave a try. Please review my pull request: https://github.com/TryGhost/mobiledoc-kit/pull/11, which fixed this problem perfectly on Chrome. but still have problem on Safari.
